---

- name: IntelMQ manager | set repo facts
  set_fact:
    __repo_install_path: /usr/share/intelmq-manager/
  tags: install

- name: IntelMQ manager | establish git
  package:
    name: git
    state: present
  tags: install

- name: IntelMQ manager | fetch repository
  git:
    repo: "{{ intelmq_manager['repo'] | default(intelmq_manager['official_repo']) }}"
    dest: "{{ __repo_install_path }}"
    version: "develop"
    force: true
  tags: install

- name: IntelMQ manager | apply path patch
  patch:
    src: "{{ __repo_install_path }}/debian/patches/fix-paths.patch"
    remote_src: true
    strip: 1
    basedir: "{{ __repo_install_path }}"
  tags: install

- name: IntelMQ manager | establish symlink within IntelMQ manager
  file:
    src: "{{ __repo_install_path }}/intelmq-manager"
    path: "{{ intelmq_manager['web_installation_path'] }}"
    state: link
  tags: install

- name: IntelMQ manager | establish positions.conf configuration file
  when: intelmq_manager['configuration_file'] is not defined
  copy:
    src: "{{ intelmq_manager['configuration_file'] }}"
    dest: "{{ intelmq_manager['configuration']['file']['path'] }}/positions.conf"
    owner: intelmq
    group: intelmq
    mode: "g+w"
    remote_src: true
  tags: configure
