---

- name: IntelMQ | set tmp repo path
  set_fact:
    __tmp_package_path: /tmp/
    __tmp_repo_path: /tmp/intelmq
  tags: install

- name: IntelMQ | establish dependencies
  package:
    name:
      - git
      - dh-make
      - dh-systemd
      - quilt
      - safe-rm
      - devscripts
    state: present
  tags: install

- name: establish python packaging dependencies
  package:
    name: 
      - python3-setuptools
    state: latest     
  tags: install

- name: IntelMQ | load online repository
  git:
    repo: "{{ intelmq['install']['repo'] | default(intelmq['official_repo']) }}"
    dest: "{{ __tmp_repo_path }}" 
    version: "develop"
    force: yes
  tags: install

- name: IntelMQ | copy over package creating script
  copy:
    src: create_deb_package.sh
    dest: /tmp/create_deb_package.sh
  tags: install

- name: IntelMQ | create custom package
  shell: "bash {{ __tmp_package_path }}/create_deb_package.sh"  
  args:
    chdir: "{{ __tmp_repo_path }}"
  tags: install

- name: IntelMQ | install generated package
  shell: "dpkg --force-confdef -i intelmq*.deb"
  args:
    chdir: "{{ __tmp_package_path }}"
  tags: install

- name: IntelMQ | remove package files
  shell: "rm -rf intelmq_*"
  args:
    chdir: "{{ __tmp_repo_path }}"
  tags: install

