---

- name: configure intelmq
  import_tasks: system.yml

- name: configure intelmq logging
  import_tasks: logging.yml

- name: configure intelmq-manager web interface
  import_tasks: webui.yml
  when: install_gui
