---

- name: IntelMQ | establish dependencies
  package:
    name: "{{ intelmq['dependencies'] }}"
    state: present
  tags: install

- name: IntelMQ | establish proper dateutil
  apt:
    deb: http://cz.archive.ubuntu.com/ubuntu/pool/main/p/python-dateutil/python3-dateutil_2.6.1-1_all.deb
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version < "18"
  tags: install

- name: IntelMQ | establish 'intelmq' group
  group:
    name: intelmq
    state: present
  tags: install

- name: IntelMQ | establish 'intelmq' user
  user:
    name: intelmq
    group: intelmq
    system: true
  tags: install

- name: IntelMQ | establish official package
  when: intelmq['install']['source'] == 'package'
  block:
    - include_tasks: "package/Debian.yml"
      when: ansible_os_family == "Debian"

    - name: IntelMQ | establish IntelMQ
      package:
        name: intelmq
        state: present
  tags: install

- name: IntelMQ | establish repo
  import_tasks: establish_intelmq_from_repo.yml
  when: intelmq['install']['source'] == 'repo'

- name: IntelMQ | establish permissons
  file:
    path: "{{ item.path }}"
    owner: "intelmq"
    group: "intelmq"
    mode: "{{ item.mode | default('g+rw') }}"
    recurse: "{{ item.recurse | default('no') }}"
    state: directory
  with_items:
    - path: "{{ intelmq['bot_config_path'] }}"
    - path: "/var/log/intelmq"
      recurse: true
    - path: "/var/lib/intelmq/bots/file-output/"
  tags: install

- name: IntelMQ | ensure log-file presence
  file:
    path: "/var/log/intelmq/intelmqctl.log"
    state: touch
  tags: install

- name: load configuration files
  when:
    - intelmq['configuration_file'] is defined
    - intelmq['configuration_file'] | length > 0
  copy:
    src: "{{ item }}"
    dest: "/etc/intelmq/{{ item | basename }}"
    owner: intelmq
    group: intelmq
    mode: preserve
  loop: "{{ intelmq['configuration_file'] }}"
  tags: configure
