---

- name: IntelMQ manager | establish package
  when: intelmq_manager['install']['source'] == 'package'
  block:
    - import_tasks: "package/Debian.yml"
    
    - name: IntelMQ manager | establish package 
      package:
        name: intelmq-manager
        state: present 
      tags: install

- name: IntelMQ manager | establish configuration directory
  file:
    path: "{{ intelmq_manager['configuration']['file']['path'] }}"
    owner: intelmq
    group: intelmq
    mode: "g+rw"
    state: directory
  tags: install

- name: IntelMQ manager | establish repo
  import_tasks: establish_intelmq_manager_from_repo.yml
  when: intelmq_manager['install']['source'] == 'repo'

- name: IntelMQ manager | ensure user 'www-data' belongs to the 'intelmq' group
  user:
    name: "www-data"
    groups: "intelmq"
  tags: install

- name: IntelMQ manager | allow webserver to execute IntelMQ
  copy:
    src: intelmq-manager/sudoers_intelmq
    dest: /etc/sudoers.d/intelmq
  tags: install



- name: IntelMQ manager | ensure log-file presence
  file:
    path: "/var/log/intelmq/intelmqctl.log"
    state: file
  tags: install

- name: IntelMQ manager | establish permissons
  file:
    path: "{{ item }}"
    owner: "intelmq"
    group: "intelmq"
    mode: "g+rw"
    recurse: yes
  with_items: 
    - "/etc/intelmq"
    - "/var/log/intelmq"
    - "/var/lib/intelmq/bots/file-output/"
  tags: install

- block:
    - name: IntelMQ manager | establish dependencies
      package:
        name:
          - python-passlib
          - python3-passlib
        state: present
      tags: install

    - name: IntelMQ manager | establish password file
      htpasswd: 
        path: "{{ intelmq_manager['authorization']['file']['path'] }}"
        name: "{{ intelmq_manager['authorization']['user']['name'] }}"
        owner: root
        mode: "u=rw,go="
        password: "{{ intelmq_manager['authorization']['user']['password'] }}"
      tags: configure
  when:
    - intelmq_manager['authorization']
    - intelmq_manager['authorization']['file']

- block:
    - name: IntelMQ manager | enable apache2 'headers' module
      apache2_module:
        name: headers
        state: present
      notify: restart apache2

    - name: IntelMQ manager | establish website in apache
      template:
        src: intelmq-manager/100-intelmq.conf 
        dest: "{{ apache_path }}/sites-available/100-intelmq.conf"
      notify: restart apache2

    - name: IntelMQ manager | enable website in apache
      file:
        src: "{{ apache_path }}/sites-available/100-intelmq.conf"
        path: "{{ apache_path }}/sites-enabled/100-intelmq.conf"
        state: link
      notify: restart apache2
  
  vars:
    apache_path: /etc/apache2/
  tags: configure
