---
# tasks file for intelmq-manager

- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python3-passlib
    - python-passlib
  tags: install

- name: ensure proper www-dir permissions
  file:
    path: /var/www/html/
    owner: "www-data"
    group: "www-data"
  tags: configure

- name: introduce intelmq repo key
  apt_key: 
    url: https://download.opensuse.org/repositories/home:sebix:intelmq/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present
  tags: install

- name: ensure intelmq repo presence
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_{{ ansible_distribution_version }}/ /
    state: present
    update_cache: yes
  tags: install

- name: install intelmq-manager
  package:
    name: intelmq-manager
    state: present
  tags: install

- name: ensure user 'www-data' belongs to the 'intelmq' group
  user:
    name: "www-data"
    groups: "intelmq"
  tags: configure

- name: ensure configuration folder existence
  file:
    path: "{{ intelmq_manager.config_file_path }}"
    owner: intelmq
    group: intelmq
    mode: "g+rw"
    state: directory
  tags: configure

- name: initialize positions.conf file
  copy:
    src: "empty.conf"
    dest: "{{ intelmq_manager.config_file_path }}/positions.conf"
    owner: intelmq
    group: intelmq
    mode: "g+w"
  tags: configure

- name: allow webserver to execute intelmq
  copy:
    src: intelmq-manager/sudoers_intelmq
    dest: /etc/sudoers.d/intelmq
  tags: configure

- name: add password file
  htpasswd: 
    path: "{{ intelmq_manager.password_file }}"
    name: "{{ intelmq_manager.user }}"
    owner: root
    mode: "u=rw,go="
    password: "{{ intelmq_manager.password }}"
  tags: configure

- name: ensure log-file presence
  file:
    path: "/var/log/intelmq/intelmqctl.log"
    state: touch

- name: fix permissons
  file:
    path: "{{ item.path }}"
    owner: "intelmq"
    group: "intelmq"
    mode: "{{ item.mode }}"
  with_items: 
  - { path: "/etc/intelmq", mode: "g+rw" }
  - { path: "/var/log/intelmq", mode: "g+rw" }
  - { path: "/var/log/intelmq/intelmqctl.log", mode: "g+rw" }
  - { path: "/var/lib/intelmq/bots/file-output/", mode: "g+rw" }
  tags: configure

- name: update apache configuration
  template:
    src: intelmq-manager/100-intelmq.conf 
    dest: /etc/apache2/sites-available/intelmq.conf
  notify: restart apache2
  tags: configure
